### ISSUE TITLE
[BUG] Can't load DaedalusX64 save file on any pc n64 emulator and vice versa 

### ISSUE THREAD

**Issue by volt72** [DaedalusX64/daedalus#11]
Describe the bug
I want to use my Pokemon Stadium save on a pc to use the Transfer pak emulation since daedalus doesn't support it. I also noticed any pc n64 emulator save file will not load in daedalus either.

To Reproduce
Open Pokemon Stadium on  DaedalusX64 then try to load the save file on any pc n64 emulator.

Expected behavior
I expected it to load my save file.

Device:
 - Device: PSP 2000
 - FW: 6.61 PRO-C infinity 2
 - Daedalus Version 1.1.8

Additional context
In the future could DaedalusX64 support transfer pak emulation?

**Comment by wally4000** [comment]
Save support has been fixed in 1.1.9
Transfer Pak emulation may come in future, thanks for the suggestion :)

**Comment by PKMNSt2** [comment]
This was not solved and the thread should not be closed but I found a solution for those in need.
https://gbatemp.net/threads/release-daedalusx64-n64-emulator.562195/page-32

Download the save file converter uploaded by Craftyawesome in the linked thread above. 
How to use the converter:
1-Place the save file in the same folder as converter
2-Drag save on converter
3-Type the name of the save you want to convert including extension, example Pokemon2.fla
4-Type the name of the new save AND its extension, example Pokemon3.fla
Note: This works both ways, To Daedalus and From Daedalus
Enjoy

**Comment by RealLittlemrh** [comment]
Hey, would this work for say harvest moon 64.mpk to harvestmoon.sav

**Comment by RealLittlemrh** [comment]
IT WORKED (used the .sra file and converted it to the .sra that project64 uses aka the a name it likes and that got it working!!!!!
